spring:
  datasource:
    url: jdbc:h2:mem:test_h2_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
  h2:
    console.enabled: true